name: deploy

# Only run this when the main branch changes
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - assets/**

# This job installs dependencies, build the site, and pushes it to `gh-pages``
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install python
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # Install R
    - name: Set up R 4.0.3
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.0.3

    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt

    - name: Install R dependencies
      run: |
        Rscript setup.R

    # Build the site
    - name: Build the site
      run: |
        python -m invoke build

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/
